Диплом.
LenzFF/explore-with-me pull request #1
Opened 2023-07-12 13:07 UTC by LenzFF

Сервис статистики
Итерация - 1

2023-07-12 23:25 UTC, db-exp requested changes

2023-07-12 23:25 UTC, db-exp commented on stats-service/stat-client/src/main/java/ru/practicum/StatClient.java
> +        RestTemplateBuilder builder = new RestTemplateBuilder();
лучше RestTemplate сделать отдельным бином

2023-07-12 23:25 UTC, db-exp commented on stats-service/stat-client/src/main/java/ru/practicum/StatClient.java
> +public class StatClient {
Клиент лучше сделать сервисом

2023-07-12 23:25 UTC, db-exp commented on stats-service/stat-dto/src/main/java/ru/practicum/dto/EndpointHitDto.java
> +public class EndpointHitDto {
еще можно Size на String поля

2023-07-13 09:36 UTC, db-exp commented on stats-service/stat-client/src/main/java/ru/practicum/StatClient.java
> +        RestTemplate rest = new RestTemplateBuilder().uriTemplateHandler(new DefaultUriBuilderFactory(baseUrl)).build();
в следующих работах перенеси в бин, пожалуйста

2023-07-13 09:36 UTC, db-exp approved these changes

2023-07-13 10:02 UTC, LenzFF commented on stats-service/stat-client/src/main/java/ru/practicum/StatClient.java
> +        RestTemplate rest = new RestTemplateBuilder().uriTemplateHandler(new DefaultUriBuilderFactory(baseUrl)).build();
@Bean
    public RestTemplate getRestTemplate() {
        return new RestTemplateBuilder().uriTemplateHandler(new DefaultUriBuilderFactory(baseUrl)).build();
    }

Вот так?

2023-07-13 13:57 UTC, merged